function Body() {
  return (
    <div style={{ margin: "80px" }}>
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...

      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...
      Some text goes here...

    </div>
  );
}

export default Body;
